# Shell utils
brew "lsd"
brew "bat"
brew "fzf"
brew "zoxide"
brew "ripgrep"

# Dev
brew "python@3.12"
brew "poetry"
brew "pyenv"
brew "node"
brew "yarn"
brew "docker"
brew "neovim"
brew "modular"
brew "tmux"
brew "lazydocker"

# Git
brew "gh"
brew "ghq"
brew "git"
brew "lazygit"
